-- Insert certificate data directly into portfolio_courses table
INSERT INTO public.portfolio_courses (
  title, subtitle, description, provider, course_type, completion_date, 
  duration, skills_learned, document_name, document_type, document_size, 
  document_url, is_featured, is_published, sort_order
) VALUES 
(
  'Python Essentials 1',
  'PCAP - Programming Essentials in Python',
  'Comprehensive Python programming fundamentals covering syntax, data structures, and object-oriented programming concepts.',
  'Cisco Networking Academy',
  'Certification',
  '2025-07-07',
  '70 hours',
  ARRAY['Python Programming', 'Data Structures', 'OOP', 'File Handling', 'Exception Handling'],
  'Python Essential 1.pdf',
  'pdf',
  2048000,
  '/certificates/Python Essential 1.pdf',
  true,
  true,
  1
),
(
  'Introduction To Cybersecurity',
  'Network Security Fundamentals',
  'Essential cybersecurity concepts including threat analysis, risk management, and security protocols.',
  'Cisco Networking Academy',
  'Certification',
  '2025-07-19',
  '30 hours',
  ARRAY['Network Security', 'Threat Analysis', 'Risk Management', 'Security Protocols', 'Incident Response'],
  'Introduction To Cybersecurity.pdf',
  'pdf',
  1856000,
  '/certificates/Introduction To Cybersecurity.pdf',
  true,
  true,
  2
),
(
  'Getting Started with Cisco Packet Tracer',
  'Network Simulation and Modeling',
  'Hands-on experience with Cisco Packet Tracer for network simulation, configuration, and troubleshooting.',
  'Cisco Networking Academy',
  'Certification',
  '2025-10-14',
  '2 hours',
  ARRAY['Network Simulation', 'Cisco Packet Tracer', 'Network Configuration', 'Troubleshooting', 'Network Design'],
  'Getting_Started_with_Cisco_Packet_Tracer_certificate_kutloano-moshao-bothouniversity-com.pdf',
  'pdf',
  1750000,
  '/certificates/Getting_Started_with_Cisco_Packet_Tracer_certificate_kutloano-moshao-bothouniversity-com.pdf',
  true,
  true,
  3
),
(
  'Virtual Internship Program',
  'Sokul Automation - 360 Hours',
  'Completed 360 hours of live delivery and work experience at Sokul Automation. Developed remote work, group work, and presentation skills while completing project-based virtual internship.',
  'Virtual Internships',
  'Internship',
  '2024-10-11',
  '360 hours',
  ARRAY['Remote Work', 'Group Collaboration', 'Project Management', 'Presentation Skills', 'Career Development'],
  'Kutloano Moshao - emkay618@gmail.com - End of Program Certificate.pdf',
  'pdf',
  1500000,
  '/certificates/Kutloano Moshao - emkay618@gmail.com - End of Program Certificate.pdf',
  true,
  true,
  4
),
(
  'Virtual Internship Report',
  'End of Program Documentation',
  'Comprehensive report documenting the virtual internship experience, project outcomes, and skills development during the 360-hour program.',
  'Virtual Internships',
  'Report',
  '2024-10-11',
  '360 hours',
  ARRAY['Technical Documentation', 'Project Analysis', 'Reflection', 'Professional Writing'],
  'Kutloano Moshao - emkay618@gmail.com - End of Program Report.pdf',
  'pdf',
  2000000,
  '/certificates/Kutloano Moshao - emkay618@gmail.com - End of Program Report.pdf',
  false,
  true,
  5
),
(
  'Academic Excellence Award',
  'Feb-June 2022 Semester',
  'Academic excellence award received for outstanding performance during the Feb-June 2022 semester at Botho University.',
  'Botho University',
  'Academic Award',
  '2022-06-30',
  '1 semester',
  ARRAY['Academic Excellence', 'Consistent Performance', 'Dedication'],
  'Feb-June-2022.pdf',
  'pdf',
  1200000,
  '/certificates/Feb-June-2022.pdf',
  true,
  true,
  6
),
(
  'Academic Excellence Award',
  'Jan-June 2024 Semester',
  'Academic excellence award received for outstanding performance during the Jan-June 2024 semester at Botho University.',
  'Botho University',
  'Academic Award',
  '2024-06-30',
  '1 semester',
  ARRAY['Academic Excellence', 'Consistent Performance', 'Leadership'],
  'Jan-June-2024.pdf',
  'pdf',
  1200000,
  '/certificates/Jan-June-2024.pdf',
  true,
  true,
  7
),
(
  'Academic Excellence Award',
  'July-Dec 2024 Semester',
  'Academic excellence award received for outstanding performance during the July-Dec 2024 semester at Botho University.',
  'Botho University',
  'Academic Award',
  '2024-12-31',
  '1 semester',
  ARRAY['Academic Excellence', 'Consistent Performance', 'Innovation'],
  'July-Dec-2024.pdf',
  'pdf',
  1200000,
  '/certificates/July-Dec-2024.pdf',
  true,
  true,
  8
);